# Generated by Django 3.0.5 on 2020-06-23 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempcustomers',
            name='str_user_contact',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tempcustomers',
            name='str_user_fax',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='tempcustomers',
            name='str_user_tel',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
