# Generated by Django 3.0.5 on 2020-06-23 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0002_auto_20200623_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempcustomers',
            name='str_user_contact',
            field=models.TextField(null=True),
        ),
    ]
