# Generated by Django 3.0.4 on 2020-03-16 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_tdealer_tnamelist_tuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='UlAuthority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('int_auth', models.IntegerField(default=0)),
                ('str_auth', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Authority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('int_user', models.IntegerField(default=0)),
                ('int_auth', models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='tracking.UlAuthority')),
            ],
        ),
    ]
