# Generated by Django 3.0.5 on 2020-06-24 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0003_auto_20200623_1149'),
    ]

    operations = [
        migrations.CreateModel(
            name='TRentalFeeDetail',
            fields=[
                ('int_rental_fee_detail_id', models.AutoField(primary_key=True, serialize=False)),
                ('int_unit_id', models.IntegerField()),
                ('int_detail_group_id', models.IntegerField()),
                ('int_detail_type_id', models.IntegerField()),
                ('int_detail_item_id', models.IntegerField()),
                ('bol_taxable_flg', models.BooleanField(blank=True, null=True)),
                ('flt_month_minute', models.FloatField(blank=True, null=True)),
                ('int_amount', models.IntegerField(blank=True, null=True)),
                ('int_tax', models.IntegerField(blank=True, null=True)),
                ('int_amount_with_tax', models.IntegerField(blank=True, null=True)),
                ('int_fee_cycle', models.IntegerField(blank=True, null=True)),
                ('int_period_from', models.IntegerField(blank=True, null=True)),
                ('int_period_to', models.IntegerField(blank=True, null=True)),
                ('int_payee_account_id', models.IntegerField(blank=True, null=True)),
                ('bol_bring_flg', models.BooleanField(blank=True, null=True)),
                ('bol_management_consignment_obj_flg', models.BooleanField(blank=True, null=True)),
                ('int_management_consignment_calc_type', models.IntegerField(blank=True, null=True)),
                ('int_period_start_month', models.IntegerField(blank=True, null=True)),
                ('bol_reward_flg', models.BooleanField(blank=True, null=True)),
                ('bol_include_administrative_flg', models.BooleanField(blank=True, null=True)),
                ('bol_include_parking_flg', models.BooleanField(blank=True, null=True)),
                ('int_vat_type', models.IntegerField()),
                ('bol_actual_cost', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': '"public"."t_rental_fee_detail"',
                'managed': False,
            },
        ),
    ]
