# Generated by Django 3.0.4 on 2020-03-16 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0004_authority_ulauthority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authority',
            name='int_user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='tracking.TUser'),
        ),
    ]
