# Generated by Django 3.0.5 on 2020-11-17 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0006_auto_20201117_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerrequirement',
            name='int_tracking_potential_customers_id',
            field=models.IntegerField(unique=True),
        ),
    ]
