# Generated by Django 3.0.5 on 2020-11-17 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0008_auto_20201117_1713'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerrequirement',
            old_name='bol_consgruction_other',
            new_name='bol_construction_other',
        ),
    ]
