# Generated by Django 3.0.5 on 2020-11-18 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0009_auto_20201117_1832'),
    ]

    operations = [
        migrations.CreateModel(
            name='TlMainStructure',
            fields=[
                ('int_main_structure_id', models.AutoField(primary_key=True, serialize=False)),
                ('str_main_structure', models.CharField(max_length=100)),
                ('str_export_1', models.CharField(blank=True, max_length=100, null=True)),
                ('str_export_2', models.CharField(blank=True, max_length=100, null=True)),
                ('str_export_3', models.CharField(blank=True, max_length=100, null=True)),
                ('str_export_4', models.CharField(blank=True, max_length=100, null=True)),
                ('str_export_5', models.CharField(blank=True, max_length=100, null=True)),
                ('str_export_6', models.CharField(blank=True, max_length=100, null=True)),
                ('str_export_7', models.CharField(blank=True, max_length=100, null=True)),
                ('str_export_8', models.CharField(blank=True, max_length=100, null=True)),
                ('str_export_9', models.CharField(blank=True, max_length=100, null=True)),
                ('str_export_10', models.CharField(blank=True, max_length=100, null=True)),
                ('str_export_11', models.CharField(blank=True, max_length=100, null=True)),
                ('str_export_12', models.CharField(blank=True, max_length=100, null=True)),
                ('str_export_13', models.CharField(blank=True, max_length=100, null=True)),
                ('str_export_14', models.CharField(blank=True, max_length=100, null=True)),
                ('str_export_15', models.CharField(blank=True, max_length=100, null=True)),
                ('str_export_16', models.CharField(blank=True, max_length=100, null=True)),
                ('str_export_17', models.CharField(blank=True, max_length=100, null=True)),
                ('str_export_18', models.CharField(blank=True, max_length=100, null=True)),
                ('str_export_19', models.CharField(blank=True, max_length=100, null=True)),
                ('str_export_20', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tl_main_structure',
                'managed': False,
            },
        ),
    ]
