# Generated by Django 3.0.5 on 2020-11-18 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0010_tlmainstructure'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tlmainstructure',
            table='"public"."tl_main_structure"',
        ),
    ]
