# Generated by Django 3.0.5 on 2020-11-18 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0011_auto_20201118_1554'),
    ]

    operations = [
        migrations.CreateModel(
            name='UlMainStructureCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('str_main_structure', models.CharField(max_length=100)),
            ],
        ),
    ]
