# Generated by Django 3.0.5 on 2020-11-18 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0012_ulmainstructurecategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='UlLayoutCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('str_layout', models.CharField(max_length=100)),
                ('int_category', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='ulmainstructurecategory',
            name='int_category',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
