# Generated by Django 3.0.5 on 2020-11-19 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0013_auto_20201118_1618'),
    ]

    operations = [
        migrations.CreateModel(
            name='TlLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('int_line_id', models.IntegerField(blank=True)),
                ('str_line', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TlStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('int_line_id', models.IntegerField(blank=True)),
                ('int_station_id', models.IntegerField(blank=True)),
                ('str_station', models.CharField(max_length=100)),
            ],
        ),
    ]
