# Generated by Django 3.0.5 on 2020-11-24 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0014_tlline_tlstation'),
    ]

    operations = [
        migrations.CreateModel(
            name='TlArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('int_area_id', models.IntegerField(blank=True)),
                ('str_area', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TlOtherCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('int_other_condition_id', models.IntegerField(blank=True)),
                ('str_other_condition', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TlSchoolArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('int_school_area_id', models.IntegerField(blank=True)),
                ('str_school_area', models.CharField(max_length=100)),
            ],
        ),
    ]
